// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGGmWjVipZaJJyOAWQiI2F-gh0ArmsGLE',
    appId: '1:625744987080:android:60df7bd5672baa718976fd',
    messagingSenderId: '625744987080',
    projectId: 'shoppingapp-f8b55',
    storageBucket: 'shoppingapp-f8b55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZpwgA___grPQMIFIYKjI46XSz53K0KEQ',
    appId: '1:625744987080:ios:8bd2dfa6213d66ec8976fd',
    messagingSenderId: '625744987080',
    projectId: 'shoppingapp-f8b55',
    storageBucket: 'shoppingapp-f8b55.firebasestorage.app',
    androidClientId: '625744987080-qe7mkamm8v1nslt4fkibh01jdlo6vubn.apps.googleusercontent.com',
    iosClientId: '625744987080-91f5grh56akiq4c3sfp17eflo5jia5sl.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

}